
//----------------------------------------------------
// The following code was generated by CUP v0.11a beta 20060608
// Mon Aug 19 18:19:12 CEST 2019
//----------------------------------------------------

/** CUP generated class containing symbol constants. */
public class sym {
  /* terminals */
  public static final int COMENTE = 42;
  public static final int DPIG = 36;
  public static final int AC = 20;
  public static final int CONST = 8;
  public static final int POR = 15;
  public static final int STR = 4;
  public static final int PC = 10;
  public static final int INT = 38;
  public static final int COMENT = 5;
  public static final int PRINTLN = 34;
  public static final int IDENTE = 43;
  public static final int FOR = 33;
  public static final int CP = 19;
  public static final int IGUAL = 11;
  public static final int BOOL = 37;
  public static final int DIV = 16;
  public static final int NUM = 3;
  public static final int CC = 21;
  public static final int MAIN = 7;
  public static final int EOF = 0;
  public static final int TRUE = 28;
  public static final int error = 1;
  public static final int COMA = 9;
  public static final int MENOS = 14;
  public static final int MENOR = 24;
  public static final int MOD = 17;
  public static final int IDENT = 2;
  public static final int EQ = 22;
  public static final int PRINTF = 35;
  public static final int MAYOR = 25;
  public static final int IMPORTS = 6;
  public static final int FUNC = 40;
  public static final int MAYORIG = 27;
  public static final int PACKAGE = 39;
  public static final int WHILE = 31;
  public static final int MENORIG = 26;
  public static final int NE = 23;
  public static final int STRING = 30;
  public static final int FALSE = 29;
  public static final int AP = 18;
  public static final int VAR = 32;
  public static final int MAINE = 41;
  public static final int PRINT = 12;
  public static final int MAS = 13;
}

