
//----------------------------------------------------
// The following code was generated by CUP v0.11a beta 20060608
// Fri Feb 08 19:31:38 GMT 2019
//----------------------------------------------------

/** CUP generated class containing symbol constants. */
public class sym {
  /* terminals */
  public static final int MENOREQ = 22;
  public static final int MASMAS = 3;
  public static final int MENOSMENOS = 5;
  public static final int AC = 10;
  public static final int POR = 6;
  public static final int CHAR = 28;
  public static final int ENTERO = 37;
  public static final int INT = 26;
  public static final int FOR = 32;
  public static final int CP = 9;
  public static final int NOT = 17;
  public static final int AND = 33;
  public static final int CARACTER = 38;
  public static final int OR = 34;
  public static final int DIV = 7;
  public static final int CC = 11;
  public static final int MIN = 29;
  public static final int IF = 23;
  public static final int EOF = 0;
  public static final int error = 1;
  public static final int MENOS = 4;
  public static final int EQEQ = 16;
  public static final int MENOR = 21;
  public static final int MOD = 27;
  public static final int IDENT = 36;
  public static final int EQ = 15;
  public static final int MAYOR = 19;
  public static final int ELSE = 13;
  public static final int MENOSU = 25;
  public static final int WHILE = 24;
  public static final int LEN = 31;
  public static final int MINN = 30;
  public static final int MAYOREQ = 20;
  public static final int AP = 8;
  public static final int DO = 35;
  public static final int PRINT = 14;
  public static final int MAT = 39;
  public static final int PYC = 12;
  public static final int NOTEQ = 18;
  public static final int MAS = 2;
}

