
//----------------------------------------------------
// The following code was generated by CUP v0.11a beta 20060608
// Sat Aug 03 12:21:44 GMT 2019
//----------------------------------------------------

/** CUP generated class containing symbol constants. */
public class sym {
  /* terminals */
  public static final int MENOS = 9;
  public static final int Y = 23;
  public static final int CP = 14;
  public static final int IDENT = 2;
  public static final int INT = 3;
  public static final int V = 19;
  public static final int SUM = 18;
  public static final int O = 24;
  public static final int CC = 5;
  public static final int POR = 10;
  public static final int MEN = 21;
  public static final int EXP = 17;
  public static final int AP = 13;
  public static final int DP = 6;
  public static final int F = 20;
  public static final int PROM = 15;
  public static final int EOF = 0;
  public static final int DIV = 11;
  public static final int AC = 4;
  public static final int PRINT = 12;
  public static final int error = 1;
  public static final int EQ = 7;
  public static final int PC = 16;
  public static final int MAY = 22;
  public static final int NO = 25;
  public static final int MAS = 8;
}

