
//----------------------------------------------------
// The following code was generated by CUP v0.11a beta 20060608
// Sun Aug 18 14:01:55 CEST 2019
//----------------------------------------------------

/** CUP generated class containing symbol constants. */
public class sym {
  /* terminals */
  public static final int ABS = 13;
  public static final int IDENTR = 5;
  public static final int POR = 32;
  public static final int GE = 20;
  public static final int STR = 4;
  public static final int IDENTN = 9;
  public static final int IDENTL = 8;
  public static final int STATUS = 12;
  public static final int COMENT = 10;
  public static final int IDENTC = 7;
  public static final int IDENTB = 6;
  public static final int CP = 36;
  public static final int ELSEIF = 24;
  public static final int IGUAL = 29;
  public static final int LT = 17;
  public static final int ABLT = 21;
  public static final int DIV = 33;
  public static final int NUM = 3;
  public static final int IF = 23;
  public static final int EXP = 34;
  public static final int LE = 19;
  public static final int EOF = 0;
  public static final int error = 1;
  public static final int COMA = 28;
  public static final int MENOS = 31;
  public static final int IDENT = 2;
  public static final int EQ = 15;
  public static final int SIGN = 14;
  public static final int ENDIF = 27;
  public static final int ELSE = 26;
  public static final int STRL = 37;
  public static final int THEN = 25;
  public static final int NE = 16;
  public static final int AP = 35;
  public static final int GT = 18;
  public static final int SET = 11;
  public static final int ABGT = 22;
  public static final int MAS = 30;
}

