
//----------------------------------------------------
// The following code was generated by CUP v0.11a beta 20060608
// Wed Sep 04 08:31:20 CEST 2019
//----------------------------------------------------

/** CUP generated class containing symbol constants. */
public class sym {
  /* terminals */
  public static final int PASTE = 6;
  public static final int AC = 28;
  public static final int POR = 17;
  public static final int AA = 35;
  public static final int PC = 11;
  public static final int COMENT = 2;
  public static final int IDENTE = 40;
  public static final int FOR = 7;
  public static final int CP = 27;
  public static final int NOT = 10;
  public static final int AND = 31;
  public static final int IGUAL = 12;
  public static final int CL = 34;
  public static final int IN = 37;
  public static final int OR = 32;
  public static final int DIV = 18;
  public static final int NUM = 38;
  public static final int EOL = 30;
  public static final int CC = 29;
  public static final int EXP = 19;
  public static final int ASDOUBLE = 8;
  public static final int EOF = 0;
  public static final int TRUE = 3;
  public static final int error = 1;
  public static final int COMA = 9;
  public static final int MENOS = 16;
  public static final int MENOR = 22;
  public static final int IDENT = 39;
  public static final int EQ = 20;
  public static final int MAYOR = 23;
  public static final int MAYORIG = 25;
  public static final int MENORIG = 24;
  public static final int NE = 21;
  public static final int ASIGI = 13;
  public static final int FALSE = 4;
  public static final int ASIGD = 14;
  public static final int AP = 26;
  public static final int DP = 36;
  public static final int PRINT = 5;
  public static final int AL = 33;
  public static final int MAS = 15;
}

