
//----------------------------------------------------
// The following code was generated by CUP v0.11a beta 20060608
// Wed Aug 07 14:19:01 GMT 2019
//----------------------------------------------------

/** CUP generated class containing symbol constants. */
public class sym {
  /* terminals */
  public static final int AND = 27;
  public static final int MENOS = 3;
  public static final int MENOR = 19;
  public static final int IDENT = 29;
  public static final int ELSE = 11;
  public static final int CP = 7;
  public static final int MAYOREQ = 18;
  public static final int PYC = 10;
  public static final int NOTEQ = 16;
  public static final int OR = 28;
  public static final int INT = 25;
  public static final int WHILE = 22;
  public static final int NOT = 15;
  public static final int IF = 21;
  public static final int CC = 9;
  public static final int POR = 4;
  public static final int AP = 6;
  public static final int DO = 23;
  public static final int MAYOR = 17;
  public static final int EOF = 0;
  public static final int MENOSU = 24;
  public static final int DIV = 5;
  public static final int AC = 8;
  public static final int PRINT = 12;
  public static final int error = 1;
  public static final int EQ = 13;
  public static final int ENTERO = 30;
  public static final int MENOREQ = 20;
  public static final int EQEQ = 14;
  public static final int FOR = 26;
  public static final int MAS = 2;
}

